Introduce stack change policy (#63)
* Introduce StackChangeAppInstancesPolicyExecutorTask
* light cleanup of PolicyExecutionTask implementations
* convert PoliciesValidator into a component
* add contains check to StacksCache
* Updates to domain objects and repositories
* add tableName and columnNames where appropriate to domain objects
* opt for fluent API in repositories where appropriate
* make sure to call .project(...) after a .select().from(...)
* Update .gitignore
* exclude config/*.sql
* Update sample secrets.json files
* to include reference to latest commit id that contains change-stack sample policy
* Update policies validator to emit warnings when a policy fails validation constraint
* key for StacksCache should be a stack's name
* Fix column name in HistoricalRecordRepo find
* Update how stack is looked up from StacksCache; provide byName and byId options
* Fix deploy/destroy scripts
* No longer need to patch r2dbc-mysql driver; https://github.com/mirromutth/r2dbc-mysql/issues/28 is resolved
* Move validation of each policy into PoliciesLoader; make sure StacksCache is seeded before attempting to load policies
* Delay subscription of products and releases from Pivnet
* Condense logic to retrieve candidates for scaling
* Work in progress attempting to implement change-stack logic

We still get an exception, but don't want to hold this up...

```
ERROR [cloudfoundry-client-nio-5] i.p.c.t.StackChangeAppInstancesPolicyExecutorTask: StackChangeAppInstancesPolicyExecutorTask terminated with error
org.cloudfoundry.client.v3.ClientV3Exception: CF-UnprocessableEntity(10008): Unable to use package. Ensure that the package exists and you have access to it.
	at org.cloudfoundry.reactor.util.ErrorPayloadMapper.lambda$null$2(ErrorPayloadMapper.java:55)
```